modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ZsoltMolnarrr/Gazebo/issues"
license = "All Rights Reserved"

[[mods]]
modId = "gazebo"
version = "${version}"
displayName = "Gazebos (RPG Series)"
authors = "Daedelus"
description = '''
Find gazebos in villages, hosting small spell libraries.
'''
logoFile = "icon.png"

[[dependencies.gazebo]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gazebo]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gazebo]]
modId = "spell_engine"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.gazebo]]
modId = "structure_pool_api"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "gazebo.mixins.json"
